#!/bin/sh
# Requires: imagemagick
set -e

INFILE=$1
OUTFILE=$2
SYMBOL=$3

DIMS=$(identify $INFILE | awk '{print $3}')
W=${DIMS%%x*}
H=${DIMS##*x}
convert $INFILE -depth 8 rgba:.tmp_image.raw

./rle32_rust ${SYMBOL} .tmp_image.raw ${OUTFILE} ${W}

