[package]
name = "gui"
version = "0.0.0"
edition = "2015"

[lib]
path = "lib.rs"

[dependencies]
kernel = { path = "../../Core" }
key_codes = { path = "../../../Shared/key_codes" }
embedded-images = { path = "../../../Graphics/embedded" }
#tag_safe = "*"

