#!/bin/bash
set -e

IMAGE="$1"
ARGS="$2"
QEMU_OPTS="$3"

QEMU_OPTS=$QEMU_OPTS" -net user"
QEMU_OPTS=$QEMU_OPTS" -bios /usr/share/qemu/OVMF.fd"

if false; then
	rm -rf .iso_root/
	mkdir -p .iso_root/boot/grub
	cat <<EOF > .iso_root/boot/grub/grub.cfg
set default="Tifflin"
set timeout=0
insmod efi_gop
insmod font
insmod gfxterm

loadfont /boot/grub/fonts/unicode.pf2
set gfxmode=auto
set gfxpayload=keep
terminal_output gfxterm

menuentry "Tifflin" {
	terminal_output serial
	set debug=all
	multiboot /${IMAGE##*/} ${ARGS}
}
EOF
	cp ${IMAGE} .iso_root/
	grub-mkrescue -o grub.iso .iso_root/ --modules="multiboot normal efi_gop font"
	QEMU_OPTS=$QEMU_OPTS" -boot d -cdrom grub.iso"
else
	make -C ../../Bootloaders/uefi
	dd if=/dev/zero of=fat.img bs=1k count=2880
	mformat -i fat.img -f 2880 ::
	mmd -i fat.img ::/EFI
	mmd -i fat.img ::/EFI/BOOT
	mcopy -i fat.img ../../Bootloaders/bootloader-efi.pe ::/EFI/BOOT/BOOTX64.EFI
	QEMU_OPTS=$QEMU_OPTS" -boot c -hda fat.img"
fi

qemu-system-x86_64 $QEMU_OPTS

