#!/bin/bash
set -eu

IMAGE="$1"
ARGS="$2"
QEMU_OPTS="$3"
if [[ $# -gt 3 ]]; then
	INITRD_PATH="$4"
else
	INITRD_PATH=""
fi

QEMU_OPTS=$QEMU_OPTS" -netdev user,id=usrnet1,tftp=.pxe/,bootfile=pxelinux.0"
QEMU_OPTS=$QEMU_OPTS" -boot n"

PXELINUX_DIR=/usr/lib/syslinux/

# Create PXE boot dir
rm -rf .pxe/
mkdir -p .pxe/pxelinux.cfg
if [ -e ${PXELINUX_DIR}pxelinux.0 ]; then
	cp ${PXELINUX_DIR}{pxelinux.0,mboot.c32,ldlinux.c32,libcom32.c32} .pxe/
else
	cp /usr/lib/PXELINUX/pxelinux.0 .pxe/
	cp /usr/lib/syslinux/modules/bios/mboot.c32 .pxe/
	cp /usr/lib/syslinux/modules/bios/{ldlinux.c32,libcom32.c32} .pxe/
fi
cp $IMAGE .pxe/
INITRD_TAIL=""
if [[ ! -z "$INITRD_PATH" ]]; then
	cp "$INITRD_PATH" .pxe/
	INITRD_TAIL="--- ${INITRD_PATH##*/}"
fi
cat <<EOF > .pxe/pxelinux.cfg/default
default testkern
label testkern
	kernel mboot.c32
	append ${IMAGE##*/} ${ARGS} ${INITRD_TAIL}
EOF

qemu-system-x86_64 $QEMU_OPTS
# | tail -n +2
