[package]
name = "syscalls"
version = "0.0.1"
edition = "2015"

[lib]
path = "lib.rs"

[dependencies]
syscall_values = { path = "../../Shared/syscall_values" }

[features]
native_nolink = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(arch, values("native"))'] }
